name: test

on:
  push:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo -H python -m pip install --upgrade pip
      - run: sudo -H pip install meson ninja
      - run: meson build
      - run: cd build && ninja test
